### PR TITLE
Set repositories topics.

### PR DESCRIPTION
**Pull request by jvanz**
Adds a resource in the Terraform script to allow set the topics for the repositories.

### CODE REVIEW

**Comment by jvanz** [comment]
I do not believe this change will work now as we would like. But I'm opening this to continue to work on this Tomorrow (too late already).

The `github_repository` resource allows us to create a repo. But it does now allow to update an existing one. As we do not have the repositories in the Terraform states, if we try to the resource to update the repository, Terraform will actually create a new repo. 

AFAICS, one solution is to update the script to have a resource for each repository and import the state manually. Thus, we **may** update a repository already created.  I`ll try to validate that soon.

**Comment by flavio** [comment]
You're right... we would have to manually import all the repos and then, specify the topics via terroform. I don't know how viable this is going to be

**Comment by jvanz** [comment]
I think an easy way to update all the using a simple (python?) script. It is faster than update all the repos manually and we avoid the pain of workaround Terraform provider limitations.

**Comment by flavio** [comment]
Yes, that sounds a better way to handle that.

**Comment by jvanz** [comment]
> Yes, that sounds a better way to handle that.

Cool. I'll update the PR with the script then.

**Review by ereslibre — APPROVED** [review]
Didn't try it, LGTM. Thanks @jvanz 👏

**Review by flavio — APPROVED** [review]
LGTM

**Pull request merged**
